function [wrd,prb]  = symbs(y,reg,xc,cpi)
%% SYMBS Symbolization of regressor 
% Symbolic coarse grain conversion of regressors. 
%
%INPUT:
%       reg: Regressor or time vector input for symbolization.
%       xc: Bin critical point indicesAll points in regressor space must
%           uniquely belong to one bin defined by xc.
%OUTPUT: 
%       wrd: Symbolized regressor and absolute number of occurances
%       prb: Normailized probability of word observation 

%% Definitions and preallocation

nt = length(reg);
nb = length(xc) - 1;            % Number of bins generated by critical points
symb = reg;                  
wrd = zeros(1,nt);
m = size(reg,1);

%rng = unique(reg);
y = sort(y,'ascend');
xc = y(xc); 

%% Symbolization of regressors

for i = 1:nb
    
    idx = logical(reg >= xc(i) & reg < xc(i+1));
    symb(idx) = i;
end

symb(:,1:cpi) = 0;

for i = cpi+1:nt
    tmp = 0;
    for j = 1:m       
        tmp = tmp + symb(j,i)*10^(m-j);
    end
    wrd(i) = tmp;
end

% Word concatenation to integers 
w = sort(wrd(:,cpi+1:end),'ascend');
[w,~,ind] = unique(w);
wct = accumarray(ind,1);

% Word Data
% Word unique, number of occurrences, probability of occurance
wrd = [sort(w,'ascend');wct'];
prb = (wct'/(nt-cpi));
